### ISSUE TITLE
Ticking Memory Connection (java.lang.IllegalArgumentException: id out of range)

### ISSUE THREAD

**Issue by stardustrider** [fewizz/NotEnoughIDs#24] opened 2015-10-23 17:16 UTC
http://pastebin.com/4FWd7u9j

I was having blocks appear in the place of others, though it was only visual. Right clicking on them would put 'em right.

**Comment by stardustrider** [comment] 2015-10-23 18:33
Here's a video of the weird block issue: https://youtu.be/OErDxx00500

**Comment by sfPlayer1** [comment] 2015-10-24 03:39
Block.getIdFromBlock returns -1 for blocks not added to the registry or null. This is possibly a bug in cavebiomes or a compatibility issue with it.

**Comment by mrammy** [comment] 2015-10-24 04:44
It also with OpenComputers cable at low Y levels on a super flat world if you need a case to replicate @sfPlayer1 .

**Comment by walkerjonny** [comment] 2015-10-24 11:03
I'm experiencing those graphical glitches, too. 
For example, as I placed a modded wooden door (Biomes o' Plenty, I think) it appeared first as cobblestone/dirt and when right clicking on it then the graphics were corrected to the modded wooden door.

**Comment by SvEgiiVEteR** [comment] 2015-10-24 15:51
и у меня такой же баг как на видео. ставлю лаву. а там вместо лавы камень земля или песок. кликаю правой кнопкой мыши и лава становиться лавой.

and I have the same bug as video. I put the lava. and there instead of lava stone land or sand. right click and lava to get lava.

**Comment by fewizz** [comment] 2015-10-24 17:50
@sfPlayer1 This bug has since version 1.4.0 test1. (And without mods this bug is present(Try to use bonemeal))

**Comment by SvEgiiVEteR** [comment] 2015-10-24 18:15
@fewizz от муки появляются камни и вода=)))
эх...

**Comment by fewizz** [comment] 2015-10-24 18:45
yay, fixed. Build soon.

**Comment by fewizz** [comment] 2015-10-24 19:16
[NotEnoughIDs-1.4.0Test4](https://drive.google.com/file/d/0B0GYhmakgvItNW5NZG1fV0FpSWM/view?usp=sharing)

**Comment by SvEgiiVEteR** [comment] 2015-10-24 21:35
баг пропал..но заметил визуальный глюк. ставишь лаву из ведра и она на 1 миг(меньше секунды) пропадает и возвращается. раньше такова кажется не замечал в самом майнкрафте.. но лаву я давно таким способ ставил...мог и запамятовать..

**Comment by fewizz** [comment] 2015-10-25 10:57
@SvEgiiVEteR , это вродь в ванильке уже есть. 
@stardustrider , now works?

**Comment by mrammy** [comment] 2015-10-25 10:58
Working for me anyway.

**Comment by fewizz** [comment] 2015-10-25 10:59
good =P.

**Comment by DPxKnightxZero** [comment] 2015-10-25 23:53
When you release a version let me know and I will test it.

**Comment by walkerjonny** [comment] 2015-10-26 03:22
Hmm, a similar error with the new 1.4.0Test4:
http://pastebin.com/2XG6XbGP
Maybe you should have another look into it...

**Comment by sfPlayer1** [comment] 2015-10-26 05:50
Previously (i.e. in Vanilla) this kind of bug would have gone unnoticed. Making the error optional may be doable, but there's likely still a mod bug that needs fixing. In Vanilla it'd just overflow and place the block with id 4095 if someone happens to just enough blocks registered.

**Comment by DPxKnightxZero** [comment] 2015-10-26 06:31
Yeah so I have the same error you are discussing

https://gist.github.com/DPxKnightxZero/332eed4bd54f08f1d66e

All I did was make a new world.

**Comment by walkerjonny** [comment] 2015-10-26 14:20
@sfPlayer1 
So if I understand it right, NEID could do something similar to Vanilla by placing that block with ID 31999 (normally I would say 32767, but there seems to be another limit) or the next lower free ID, if ID 31999 is already set, right?
But then still the question remains what block from which mod caused that issue...
Would be good to set a log entry for that at least.

@fewizz 
Just to let you know - the graphical glitches are gone with 1.4.0Test4. So that one seems to be fixed.

**Comment by DPxKnightxZero** [comment] 2015-10-27 04:14
I need Fewizz and Player to join my modpack and see this wierd bs. ASAP!

http://www.technicpack.net/modpack/pz-project-ultima-pts.755209/updates

If you need access to any of the files let me know.

**Comment by DPxKnightxZero** [comment] 2015-10-27 04:16
Single Player works normal.

**Comment by DPxKnightxZero** [comment] 2015-10-27 06:07
If you are wondering what error I was having? Basically Dirt kept replicating placing certain blocks doors have a wierd issue etc. I am going to leave the server up till you can see for yourself.

**Comment by DPxKnightxZero** [comment] 2015-10-27 06:34
Nevermind I will Just give you the server files XD Virus check it if you want; I would rather fix shit so I don't desire to mess with you. If you want I can do rar5 but I am compressing it as much as possible.

**Comment by DPxKnightxZero** [comment] 2015-10-27 06:46
Fuck I am slow ... 

"Here's a video of the weird block issue: https://youtu.be/OErDxx00500" My issue as well.

**Comment by fewizz** [comment] 2015-10-27 06:52
Look at 9 comment

**Comment by DPxKnightxZero** [comment] 2015-10-27 07:24
What is the latest Fastcraft?

**Comment by DPxKnightxZero** [comment] 2015-10-27 07:24
I am using test17

**Comment by sfPlayer1** [comment] 2015-10-27 08:03
is this now only broken with fc or even without it?

**Comment by DPxKnightxZero** [comment] 2015-10-27 12:15
I will be testing in the next hour please stand by.

**Comment by DPxKnightxZero** [comment] 2015-10-27 13:53
Just to let you know everything appears stable.

**Comment by walkerjonny** [comment] 2015-10-27 15:04
With what configuration?
With or wothout fastcraft? Which version?
With or without NEID (& NEID Tweaker)? Which version?

**Comment by DPxKnightxZero** [comment] 2015-10-27 23:47
With Fastcraft ctest17 and NotEnoughIDS 1.4.0

**Comment by walkerjonny** [comment] 2015-10-28 11:51
That sounds good so far!

**Comment by DPxKnightxZero** [comment] 2015-10-28 18:25
Well now we have a new issues ... some enemies are their but invisible. Also cannot be hit but using Damage Indicators can be seen. Also they appear on the journey map.

**Comment by walkerjonny** [comment] 2015-10-28 18:52
Hmm, some mods like Lykanites Mobs have some sort of invisible mobs. Are you sure that you do not have one of those mods in your modpack?

**Comment by DPxKnightxZero** [comment] 2015-10-28 18:54
Well its squids. As in min craft squids.

**Comment by walkerjonny** [comment] 2015-10-28 20:09
Hmm, I had squids last evening and they were displayed properly so far. But I'm playing SP at the moment...

**Comment by DPxKnightxZero** [comment] 2015-10-28 20:44
I can do that ;P after all it is my purpose of being on this github.

**Comment by DPxKnightxZero** [comment] 2015-10-29 00:24
Ticking Memory Glitch - Started After Adding DivineRPG and making a New world. 
https://gist.github.com/DPxKnightxZero/1b67f055a9cf89d683e0

Full Client Log after crash
https://gist.github.com/DPxKnightxZero/6962a228ec7107fcb758

**Comment by fewizz** [comment] 2015-10-30 14:45
@DPxKnightxZero , pls , try use version 1.4.0 T3 (in new world).

**Comment by DPxKnightxZero** [comment] 2015-10-31 03:42
Isn't test 4 the latest?
Also test3 wont even run.

You are doing something right in test4

**Comment by Adaptivity** [comment] 2015-11-21 18:27
Create new issue if still not fixed with steps to reproduce.

**Closed by Adaptivity** 2015-11-21 18:27 UTC
Labels: bug, fixed
