### ISSUE TITLE
IllegalArgumentException: id out of range: -1

### ISSUE THREAD

**Issue by walkerjonny** [fewizz/NotEnoughIDs#28] opened 2015-12-02 21:49 UTC
Hi, I got this crash to desktop as I was in game in the Nether.
Maybe you have an idea about the reason for this crash.
http://pastebin.com/8f07EQvZ

**Comment by accessdenied0** [comment] 2015-12-04 22:26
Hello @fewizz and @walkerjonny ,

Sorry to put me here in, but I got a similar issue. This is a small output from my console: http://pastebin.com/kNGxrhWE
and here is my crash report:
Crash Part-I in addition to my Console output (SMP- server crash):  http://pastebin.com/KaKcjtAB
Crash Part-II in addition to the Crash report after closing client: http://pastebin.com/uaD6WNWL

I'm honestly not sure what caused it,

access_denied

**Comment by Bogdan-G** [comment] 2015-12-05 01:12
@accessdenied0 the problem is reproduced without mystcraft mod? as well as like NEID 1.4.0 was supposed to be after editing and a more recent version of the FC is not present.

Check other mods that interfere in this issue.

**Comment by accessdenied0** [comment] 2015-12-07 16:07
@Bogdan-G,

From my side:

I can't figured it out what exactly caused it, but I was able to track it down to SteamCraft2. It seem SteamCraft2's Biomes made Mystcraft some trouble. In my case, after removing SteamCraft2 it seem to work just fine. Mystcraft wasn't the troublemaker.

I thank you for your help,

access_denied

**Comment by fewizz** [comment] 2015-12-07 16:09
https://github.com/BrassGoggledCoders/Steamcraft2/issues/344

**Comment by Adaptivity** [comment] 2015-12-11 15:16
Not NEID problem.

**Closed** 2016-05-12 10:31 UTC
Labels: bug, invalid
