### ISSUE TITLE
serverside Fastcraft incompatibility

### ISSUE THREAD

**Issue by DPxKnightxZero** [fewizz/NotEnoughIDs#22] opened 2015-10-17 01:53 UTC
Alright so let me start by saying on the surface this may look like a forge essentiails issue but the issue actually started after adding NotEnoughIDs. I noticed this mod greatly messes with ASM style code ... could you please attempt see what you can do? Also you should ask iPlayer for help as well. He is the creator of fastcraft.

https://gist.github.com/DPxKnightxZero/31c032cdac88b00f09eb

**Comment by sfPlayer1** [comment] 2015-10-17 03:41
I'd very much prefer if you NotEnoughIDs didn't mess with Fastcraft's code... The edits are breaking fundamental assumptions in FC, cause nasty issues like the linked one and are actually largely incomplete from my understanding of your base edits.

It's much easier to just tell me what exactly is required to establish compatibility on my side by explaining the API changes and inner workings. Contrary to other optimization mods I'm actively aiming for as much compatibility as possible.

**Comment by DPxKnightxZero** [comment] 2015-10-17 04:05
God I love you player <3

**Comment by Bogdan-G** [comment] 2015-10-17 12:59
Fixed?

**Comment by sfPlayer1** [comment] 2015-10-17 13:18
Bogdan the closed is from FE. The issue isn't fixed.

I've just implemented some compatibility on my side for the upcoming build 16, NEIDs has to remove all the Fastcraft edits for it to work though.

**Comment by fewizz** [comment] 2015-10-17 13:21
ok.

**Comment by fewizz** [comment] 2015-10-17 18:46
@sfPlayer1 compatibility code now removed. If you need something on NEID side, just ask. New NEID version will be released when you release new Fastcraft build.
[1.3.1](https://drive.google.com/file/d/0B0GYhmakgvItSFVGbUpROFdVbWM/view?usp=sharing)
[1.3.1 DEOBF](https://drive.google.com/file/d/0B0GYhmakgvItR21Vb0NRSnhrWlk/view?usp=sharing)

**Comment by sfPlayer1** [comment] 2015-10-17 18:58
Thanks, it should be fine as long as:
- the tweaker class name doesn't change (ru.fewizz.idextender.Tweaker.IETweaker)
- your mod is always active when installed
- GameData.MAX_BLOCK_ID contains the correct value
- the field block16BArray remains as-is in ExtendedBlockStorage (name, type, semantics)
If something happens to change please notify me.

I'll test if my compatibility edits work later and prepare the release afterwards.

**Comment by sfPlayer1** [comment] 2015-10-17 18:59
Ah you removed the tweaker, I'll use the loadingplugin class then.

**Comment by fewizz** [comment] 2015-10-17 19:13
Note: Method isEmpty in class ExtendedBlockStorage now always return true. I'm not sure if it's good thing. It was done for compatibility with KCauldron.

**Comment by sfPlayer1** [comment] 2015-10-18 00:13
There it is: http://files.player.to/tmp/fastcraft-1.22-ctest16.jar

**Comment by SvEgiiVEteR** [comment] 2015-10-18 01:04
I'll check at.

**Comment by SvEgiiVEteR** [comment] 2015-10-18 01:17
I'll check on my server.

and....
http://paste.org.ru/?akb6z8
a problem on the server side.

Check with version 130 or 131?

**Comment by SvEgiiVEteR** [comment] 2015-10-18 01:43
I'll check on my server.

and....
client runs with all mods
server wait ...

**Comment by fewizz** [comment] 2015-10-18 07:04
@SvEgiiVEteR, server KCauldron, Cauldron or vanilla?

**Comment by fewizz** [comment] 2015-10-18 11:34
[Client](http://pastebin.com/cBAibKRx)

**Comment by sfPlayer1** [comment] 2015-10-18 13:34
SvEgiiVEteR the first link points to an old FC version, possibly 1.21. The 2nd link is unrelated and shows no crash.

fewizz: That's because you don't set the field GameData.MAX_BLOCK_ID to the correct value yet. You need to change the field initializer with something like <MAX_BLOCK_ID fieldNode>.value = new Integer(<the actual max id>) in https://github.com/fewizz/NotEnoughIDs/blob/master/src/main/java/ru/fewizz/idextender/Transformer/IETransformer.java#L99

**Comment by fewizz** [comment] 2015-10-18 13:36
ah, ok.

**Comment by SvEgiiVEteR** [comment] 2015-10-18 13:48
sfPlayer1
so I started wrong, and forgot to remove 21. but then I fix it ...
but the problem remained. World 10 seconds break. I am looking for mod due to which this problem ..

I will wait for the new version

**Comment by fewizz** [comment] 2015-10-18 14:03
http://pastebin.com/vJiscC23

**Comment by fewizz** [comment] 2015-10-18 14:47
http://pastebin.com/6AW9L12M

**Comment by sfPlayer1** [comment] 2015-10-18 16:19
Hmm yes that's an obvious bug of mine, I'll fix shortly..

**Comment by sfPlayer1** [comment] 2015-10-18 16:24
http://files.player.to/tmp/fastcraft-1.22-ctest17.jar

**Comment by fewizz** [comment] 2015-10-18 16:44
![2015-10-18_20 42 54](https://github-cloud.s3.amazonaws.com/assets/8060034/10565056/80b085da-75d0-11e5-99aa-a1b5569afdc2.png)
woks fine(client, not teseted at server).

**Comment by DPxKnightxZero** [comment] 2015-10-18 17:03
I can test on a server but it was never an issue on a client :/

**Comment by fewizz** [comment] 2015-10-18 17:09
[latest version, without tweaker](https://drive.google.com/file/d/0B0GYhmakgvItX1gyU1gzZk9ybVE/view)

**Comment by DPxKnightxZero** [comment] 2015-10-18 17:14
Fast Craft Test 16 with NotEnoughID's 1.3.1 without updated tweaker - Serverside
https://gist.github.com/DPxKnightxZero/f13a30cfee1625d09b64

Fast Craft Test 17 with NotEnoughID's 1.3.1 without updated tweaker - Serverside
https://gist.github.com/DPxKnightxZero/adc4a8432e7a7575476d

**Comment by DPxKnightxZero** [comment] 2015-10-18 17:16
Success! After deleteing tweaker fastcraft 17 was successfully initialized.

**Comment by Adaptivity** [comment] 2015-10-18 17:20
@DPxKnightxZero please reply on issue #20. We need more info from you.

**Comment by sfPlayer1** [comment] 2015-10-18 17:21
fewizz your latest build ships a bunch of fml classes, most likely unintentionally.

**Comment by fewizz** [comment] 2015-10-18 17:22
link updated.

**Comment by stardustrider** [comment] 2015-10-18 17:49
Getting the following crash with the above new version of FastCraft:

http://pastebin.com/rctMwFTH

**Comment by sfPlayer1** [comment] 2015-10-18 17:53
That implies block16BArray has an element with the value 65535.

**Comment by DPxKnightxZero** [comment] 2015-10-18 18:01
Player I am reaching more stability in my modpack I will start adding actual author license soon. However you want me to write it I will. I know not everyone likes me and I honestly don't like every person but my plan is to create a "created by AUTHOR" next to each mod because technic does not permit hotlinks. I could also include a googldoc that has links and what not but people would actually have to learn how to use copy and paste. Same with you Fewizz.

**Comment by fewizz** [comment] 2015-10-18 18:21
@stardustrider , but without fastcraft?

**Comment by sfPlayer1** [comment] 2015-10-18 18:27
Vanilla most likely doesn't crash from it, but the value is still invalid and there must be a reason for it to get there, probably a bug in the func_150818_a edit.

**Comment by sfPlayer1** [comment] 2015-10-18 18:44
The way InsnList is being used is highly problematic, e.g. https://github.com/fewizz/NotEnoughIDs/blob/master/src/main/java/ru/fewizz/idextender/Transformer/IETransformer.java#L256

Calling InsnList.set on an AbstractInsnNode that isn't actually inside the InsnList will corrupt both "this", the list the node is actually part of and the node itself. Besides that it certainly makes the code much more difficult to understand. I'm tempted to clean it up myself ;)

**Comment by stardustrider** [comment] 2015-10-18 18:47
Just tested it, and it's fine without FastCraft

**Comment by DPxKnightxZero** [comment] 2015-10-18 18:51
They are attempting to add fastcraft compatibility make sure you use gist and upload any and all crashes after each test; list your test environment and any mods that may seem outdated or problematic. If you just say something like; "It works" or "It doesn't work" is not actually applying any sort of solution or debugging info. Thanks for reading.

**Comment by fewizz** [comment] 2015-10-18 18:52
@sfPlayer1 you already have rights for this =3. And maybe just hook method, and send all parameters:
(Hooks class)
public static void hook_func_150818_a(ExtendedBlockStorage ebs, int x, int y, int z, Block block){
    todo something
}
?

**Comment by SvEgiiVEteR** [comment] 2015-10-18 19:10
http://paste.org.ru/?y46cvu
world generate and running, but confused lines
135367

**Comment by fewizz** [comment] 2015-10-18 22:06
[try this](https://drive.google.com/file/d/0B0GYhmakgvItOFhXZFNOajA5UGs/view?usp=sharing)

**Comment by sfPlayer1** [comment] 2015-10-18 22:22
I have some major cleanup and refactoring incoming in a bit..

**Comment by SvEgiiVEteR** [comment] 2015-10-19 05:49
http://pastebin.com/fvYny5Pn

**Comment by fewizz** [comment] 2015-10-19 12:52
можешь скинуть мне модпак?

**Comment by Adaptivity** [comment] 2015-10-19 13:27
@stardustrider @SvEgiiVEteR Can you guys try [this version](https://www.dropbox.com/s/ownb6ux6u9pua3a/NotEnoughIDs-1.3.1.jar?dl=0) (This version contains @sfPlayer1's changes)? I can't reproduce your crashes at all. Make sure you are using latest fastcraft test build and NEID tweaker is NOT installed.

**Comment by sfPlayer1** [comment] 2015-10-19 14:19
Existing worlds may not recover, I'll have to think about fixing that on either side. I also didn't add checks to prevent corruption yet.

**Comment by fewizz** [comment] 2015-10-19 14:23
@sfPlayer1 , what you think about this
![image](https://cloud.githubusercontent.com/assets/8060034/10580381/f9eb5b40-7685-11e5-9232-01782dcb9800.png)
(Hooks class) already works.

**Comment by sfPlayer1** [comment] 2015-10-19 14:24
fewizz I'm doing that in bytecode already, see the comments

**Comment by SvEgiiVEteR** [comment] 2015-10-19 15:10
fewizz  могу дать тока через эту программу.
https://github.com/canton7/SyncTrayzor/releases
папки конфиг и моды.
я пробовал https://drive.google.com/file/d/0B0GYhmakgvItOFhXZFNOajA5UGs/view?usp=sharing
может из за неё проблема. сейчас ещё проверять будет.

**Comment by SvEgiiVEteR** [comment] 2015-10-19 15:27
Adaptivity 
with your version of another mistake ...
http://pastebin.com/vPHBbHVq

**Comment by fewizz** [comment] 2015-10-19 15:29
@SvEgiiVEteR  crashes only on server, i think?

**Comment by sfPlayer1** [comment] 2015-10-19 15:30
I haven't fixed this part yet, the asm edits there damage the local variable table. With the newly added validator it's crashing. Expect a fix presumably later today.

**Comment by fewizz** [comment] 2015-10-19 15:32
![image](https://cloud.githubusercontent.com/assets/8060034/10582238/8b720c0e-768f-11e5-9286-79487cfe3375.png)
ported from bukkit, fixes comp. with [KCauldron](https://gitlab.prok.pw/Prototik/KCauldron/blob/master/patches/net/minecraft/world/chunk/storage/ExtendedBlockStorage.java.patch#L35). What you think about this, @sfPlayer1 ?

**Comment by SvEgiiVEteR** [comment] 2015-10-19 15:34
fewizz  да
с вашей последней версией для stardustrider 
и от Adaptivity 
а предпоследня вроде работает.
только сел проверять.
translate tired)))

**Comment by sfPlayer1** [comment] 2015-10-19 15:39
fewizz that's merely an optimization which FC already does in a better way. I'd keep this mod to compatibility fixes only.

SvEgiiVEteR I can't read russian ;)

**Comment by fewizz** [comment] 2015-10-19 15:43
I can merge this?(useful, if fastcraft is not in modpack.)

**Comment by sfPlayer1** [comment] 2015-10-19 15:44
Meh, I'd keep it simple, but it's up to you.

**Comment by SvEgiiVEteR** [comment] 2015-10-19 15:45
sfPlayer1
"Yes
with our latest version for stardustrider (this version was able to go to the server, but after 10 seconds of the crash)
and by Adaptivity
and penultimate like works.
just sat check."
I, too. basically I translate google)

**Comment by DPxKnightxZero** [comment] 2015-10-19 19:46
So I found a unique glitch after using this modset ... however its to random to pinpoint the source. Here is some images that seem to relate to the issue. I had a java test sample that said fast craft was 4 on the list for using the most processing power ... anyways this is the result. 
![2015-10-19_02 56 22](https://cloud.githubusercontent.com/assets/10351221/10589238/a97dadea-766f-11e5-851e-9bc2d86b0ad1.png)
![2015-10-19_02 56 41](https://cloud.githubusercontent.com/assets/10351221/10589237/a97909de-766f-11e5-9926-824138a94d6b.png)
It appears link an entire chunk row was missing ... the wierd thing is walking in it caused the entire screen to go blue.

Another weird thing is if you walked about 100 blocks away and went back it seems to fix itself re-logging in however did not.

**Comment by SvEgiiVEteR** [comment] 2015-10-19 20:20
@DPxKnightxZero 
I can say that the penultimate version works
MD5: 031048bdfcbaec37d80cb75c70f8b07a
The other two are laid out later. cause problems with the world.
modpack....
install the program.
https://github.com/canton7/SyncTrayzor/releases
and tell me your ID. and I will give the mods folder and configs.
if I did not cause any problems, I would certainly put to something mod pack ...
now it is the easiest and fastest way for me
excuse me..

my id
YUP6O72-HZKJHUG-7GDQHRN-PIC6SP6-BXRO4DG-5A7E4SS-CBIJHVX-C3Z5TAD

**Comment by DPxKnightxZero** [comment] 2015-10-19 20:23
.... error what prevents you from just upload to mega?
Nevermind I will try this ... (Never heard of it before now.) Also I planned on doing my own test but um kay.

**Comment by DPxKnightxZero** [comment] 2015-10-19 20:27
Um my id? 

OHZFYAF-IQCPEDG-5W7JUS5-HLGQA46-ZRDDBIQ-U2D26MO-GU5KH5B-ZE6FRAB

**Comment by SvEgiiVEteR** [comment] 2015-10-19 20:30
the computer is too busy. because of the test ....
mod pack requires a lot of resources of a PC
I try to put on the Mega. folder modes and configs you enough?
Yes that's right if it does not, then put on a mega

**Comment by sfPlayer1** [comment] 2015-10-19 21:24
fewizz the last merge may have dropped something, please verify. Otherwise the changes are not significantly tested.

**Comment by Adaptivity** [comment] 2015-10-20 04:46
@DPxKnightxZero this bug caused not by NEID. This all I can say you. I remember it happened to me few times years ago.
@sfPlayer1 May this bug be related to Fastcraft? I just reproduced it with this [setup](http://i.imgur.com/ohlehLi.jpg). And heres few [screenshots](http://imgur.com/a/4TdDY)
Relogging however does fixes this in my case (I'm in singleplayer).
Also, I just compiled NEID source and now I'm unable to start the game: http://pastebin.com/cd0ReFWH

**Comment by Bogdan-G** [comment] 2015-10-20 07:19
Missing chunks or strip chunks is a bug vanilla.

**Comment by fewizz** [comment] 2015-10-20 09:30
@sfPlayer1 , everything is ok.

**Comment by fewizz** [comment] 2015-10-20 11:32
[NotEnoughIDs-1.4.0Test1](https://drive.google.com/file/d/0B0GYhmakgvItZjMzVmtoT2RSY2s/view?usp=sharing)

**Comment by SvEgiiVEteR** [comment] 2015-10-20 14:23
http://pastebin.com/QGihrHrP

**Comment by Adaptivity** [comment] 2015-10-20 14:43
@SvEgiiVEteR strange crash, @fewizz looking into it right now.
I guess we all now should praise @sfPlayer1. His latest changes to the code made impossible (Well, we thought so) - possible. You can now load your old saves with NEID installed. It wasn't highly tested but it's works. Congrats @sfPlayer1 and thank you!

**Comment by SvEgiiVEteR** [comment] 2015-10-20 14:59
and the log if help ...
http://paste.org.ru/?bkv1kq

**Comment by Bogdan-G** [comment] 2015-10-20 15:12
@Adaptivity mod NEID not working,

**Comment by fewizz** [comment] 2015-10-20 16:15
@sfPlayer1 for some reason cpw.mods.fml.common.registry.GameData is not sending to transformer.  Maybe Is it because Sorting Index used here?

**Comment by sfPlayer1** [comment] 2015-10-20 16:22
The sorting index shouldn't make any difference there, at least unless no coremod accesses this class too early, which is obviously broken behavior. I'll have a look later.

**Comment by fewizz** [comment] 2015-10-20 16:25
ok.

**Comment by sfPlayer1** [comment] 2015-10-20 17:20
I'm improving error handling atm...

**Comment by sfPlayer1** [comment] 2015-10-20 20:06
I've figured out that it's fml itself doing the early class loads. I've switched back to obf names with some improvements to the name system to handle both obf (vanilla classes) and srg (mod classes) names at the same time.

**Comment by sfPlayer1** [comment] 2015-10-20 20:08
You're now supposed to throw AsmTransformerException after detecting a faulty to make it easy to identify the issue. AsmUtil.findMethod/findField throw errors by default if they don't find anything, there's alternative versions for optional lookups.

**Comment by fewizz** [comment] 2015-10-20 21:25
[crash](http://pastebin.com/8x7aFbCd) , i think that problem in one of the Packets.

**Comment by sfPlayer1** [comment] 2015-10-21 01:54
Check the log/console output, there should be something more helpful.

**Comment by fewizz** [comment] 2015-10-21 06:10
[NotEnoughIDs-1.4.0Test2](https://drive.google.com/file/d/0B0GYhmakgvItano2Nkhxa3J0Qnc/view?usp=sharing)

**Comment by SvEgiiVEteR** [comment] 2015-10-21 07:03
I set ... waiting for the start ..
It seems to be no problem as the test 1
......

**Comment by walkerjonny** [comment] 2015-10-21 08:57
Log Line 121118 & 121119 should be interesting here:
[10:07:04] [Server thread/DEBUG] [NEID/]: Patching cofh.lib.util.helpers.BlockHelper with CofhBlockHelper...
[10:07:04] [Server thread/ERROR] [NEID/]: Error transforming cofh.lib.util.helpers.BlockHelper with CofhBlockHelper: can't find method MAX_ID

**Comment by fewizz** [comment] 2015-10-21 13:23
[NotEnoughIDs-1.4.0Test3](https://drive.google.com/file/d/0B0GYhmakgvItMGdUVWk3d1pBTlk/view?usp=sharing)

**Comment by SvEgiiVEteR** [comment] 2015-10-21 17:55
test3

launched, all is well.
but not all checked. Suddenly there are some other bugs)

**Comment by fewizz** [comment] 2015-10-21 17:59
good start :smile:

**Comment by SvEgiiVEteR** [comment] 2015-10-21 20:42
It may be due to compatibility?
http://pastebin.com/Hnu6NWPU
forge ok

**Comment by mrammy** [comment] 2015-10-22 11:39
http://hastebin.com/asucoxebev.avrasm after removing a block previously in the world and loading the world on the server side. Works fine without NEID with NEID crashes the world. Also with the latest build test3 it appears some blocks are being rendering funny on a super flat world. I tried with OpenComputers cables and they didn't quite want to render even though they were definately in that block space. Some other blocks like the tinkers construct seared faucet was replaced with a block of smooth stone while it was pouring and the tinker's smeltery controller vanished until i tried to click in it's block space or relogged.

**Comment by fewizz** [comment] 2015-10-22 12:34
@sfPlayer1 , block16BArray has an invalid element again?

**Comment by fewizz** [comment] 2015-10-22 13:50
@mrammy , modpack please.

**Comment by fewizz** [comment] 2015-10-22 15:56
@SvEgiiVEteR , [now works?](https://gitlab.prok.pw/Prototik/KCauldron/issues/216#note_1572)

**Comment by fewizz** [comment] 2015-10-22 16:00
@mrammy , modpack please.

**Comment by mrammy** [comment] 2015-10-22 16:02
Should be replicateable with any pack just remove a block from the list of
registered and try to load the world.

**Comment by fewizz** [comment] 2015-10-22 16:03
ah, ok.

**Comment by SvEgiiVEteR** [comment] 2015-10-22 17:30
@fewizz no..... ((
http://pastebin.com/c1JUREGe
I do not know what's going on even. I was not at home.
Now I sit on, and will check more

**Comment by mrammy** [comment] 2015-10-22 17:33
That specific error happens with or without NEID and the gravigun and
portalgun specifically in KCauldron. I doubt its NEID related. I had that
same error a month or 2 ago and its KCauldron related has nothing to do
with NEID installed.

**Comment by SvEgiiVEteR** [comment] 2015-10-22 23:29
test 3
forge
at the moment everything is fine. the world did not break.
It may have bugs with an ID modes
as written above but I still was not looking for them.

**Comment by DPxKnightxZero** [comment] 2015-10-23 11:49
Hey guys I using the latest stuff you provided Player and Fewizz I got a crash that prevents players from being able to connect serverside.

https://gist.github.com/DPxKnightxZero/4754bb7be75a180d7961 - Error Log

https://gist.github.com/DPxKnightxZero/50feb2c1657ed3403781 - Server Full log during error environment.

**Comment by DPxKnightxZero** [comment] 2015-10-23 11:57
I might be off in the data I have collected ... I am exhausted forgive me if I said sometyhing stupid.

**Comment by Bogdan-G** [comment] 2015-10-23 12:02
@DPxKnightxZero disable UpdateChecker in divineRPG

**Comment by DPxKnightxZero** [comment] 2015-10-23 12:06
OKay now minus that I got a new crash with fascraft written all over it.

**Comment by DPxKnightxZero** [comment] 2015-10-23 12:06
Tired need sleep.

**Comment by DPxKnightxZero** [comment] 2015-10-23 21:36
Okay so after removing DivineRPG something happened with Fastcraft again but with the latest buildcraft

https://gist.github.com/DPxKnightxZero/0baad7cd1ac39617ec0a <- Crash Log

Partial Crash Report - Serverside [Issue Between Buildcraft and Fastcraft] - Latest Everything Available 

https://gist.github.com/DPxKnightxZero/89b355b818afd59bbac5 <- Quickly Noticed Crash from full log

Full Report - Serverside [Issue Between Buildcraft and Fastcraft] - Latest Everything Available
https://gist.github.com/DPxKnightxZero/5b48209dc64e4c719a25 <- Full Log

Need fix ASAP thanks guys.

**Comment by sfPlayer1** [comment] 2015-10-24 03:52
git master may fix this.

**Comment by walkerjonny** [comment] 2015-10-24 15:29
I have compiled the master with sfPlayer's changes.
Here is the download link:
http://www.file-upload.net/download-10993614/NotEnoughIDs-1.4.0Test3.jar.html

**Comment by DPxKnightxZero** [comment] 2015-10-24 23:01
Weird Crash when I changed the chunk distance in game. 
@walkerjonny it did work until I changed render distance :/
https://gist.github.com/DPxKnightxZero/97fdb55a730b7a14ba6d

**Comment by fewizz** [comment] 2015-10-25 11:00
@sfPlayer1 , fastcraft bug?

**Comment by sfPlayer1** [comment] 2015-10-25 20:11
Unlikely, it's mostly pass-through type code in the stack trace. I'd have to inspect the code where it crashes, but I don't even know the mod that's crashing. It may just see an unexpected metadata value or something similar.

**Comment by DPxKnightxZero** [comment] 2015-10-25 23:54
Buildcraft and celestial craft were culprits in a few test environments. If that helps.

**Comment by DPxKnightxZero** [comment] 2015-10-26 01:02
Confirmed removing celestial craft caused things to work :D

**Comment by SvEgiiVEteR** [comment] 2015-10-27 12:17
иногда бывают подобные краши
http://hastebin.com/dabiwoleca.md
блоки бывают разные..это может быть связано с ID?
@fewizz я писал в личку на форуме IC2 не что подобно, но с другой причиной,но кажеться это связано

**Comment by Rongmario** [comment] 2015-10-30 11:30
http://hastebin.com/mihevonayo.coffee
Removing fastcraft works

**Comment by fewizz** [comment] 2015-10-30 14:46
@Rongmario you using version 1.4.0 T4?

**Comment by Rongmario** [comment] 2015-11-02 18:02
Yes am I

**Comment by Adaptivity** [comment] 2015-11-21 18:26
If any new issues arise, create new issue.

**Closed by Adaptivity** 2015-11-21 18:26 UTC
Labels: bug, compatibility, fastcraft, fixed
